enabled: true

database:
    enabled:    false
    type:       mysql
    host:       localhost
    port:       3306
    db:         database
    user:       root
    password:   root
    table:      player_list

server:         mcpe
